name: CI/CD Pipeline

on:
  push:
    branches: ["main", "deploy-testing"]
  pull_request:
    branches: ["main", "deploy-testing"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: yarn install

      - name: Start Backend Server
        working-directory: ./backend
        run: yarn serve &

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Run Cypress Tests
        working-directory: ./frontend
        env:
          VUE_APP_BACKEND_API_URL: http://localhost:3000
          VUE_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.VUE_APP_GOOGLE_MAPS_API_KEY }}
        run: |
          yarn serve &
          sleep 30
          yarn test:e2e

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy-testing'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Compose images
        env:
          VUE_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.VUE_APP_GOOGLE_MAPS_API_KEY }}
          VUE_APP_BACKEND_API_URL: ${{ secrets.VUE_APP_BACKEND_API_URL }}
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
